### ISSUE TITLE
Error , Vytal is disabled

### ISSUE THREAD

**Issue by DevilsLamb** [vytal-io/vytal-extension#28]
To re-enable it, accept the new permissions:

- Detect your physical location

Vytal stopped working unless I give it permission for location detection, can someone explain this to me? Thank you

[](url)
![Vytal ](https://user-images.githubusercontent.com/107503704/200856127-50c08814-e3a7-4501-bad4-c890092acd1d.png)

**Comment by DevilsLamb** [comment]
This happened after update to 2.1 from chrome webstore, I cant find anything like release notes on Github about this update yet.

**Comment by z0ccc** [comment]
I was going use it to show default data, but decided against it. But I forgot to remove permission. Has been fixed in the next version.

**Comment by z0ccc** [comment]
Ill leave this open until the new version is approved and published (incase anyone else has the same question)
