### ISSUE TITLE
Load Match by IP by default?

### ISSUE THREAD

**Issue by AlexPaiva** [vytal-io/vytal-extension#41]
Is there any way to make it so that when the extension loads the default option is match timezone by IP? Or can you tell me how to edit it so it stays like that? Every time I install it, I have to manually go to the option and load the setting of match timezone by IP, no way to do it automatically as default?

Thanks.

**Comment by AlexPaiva** [comment]
[z0ccc](https://github.com/vytal-io/vytal-extension/commits?author=z0ccc)
z0ccc Can you give me a hand here? I managed to make it so when the popup opens it loads the match by IP by default but I want to initiate the debugging right away and set the match by ip right away, any way to do that?

**Comment by AlexPaiva** [comment]
Did it myself, if anyone needs help comment here.

**Comment by Beetroit** [comment]
@AlexPaiva i need to know how you got it done. I am trying to use it in an automation script via selenium. Thanks
